imports:
    - { resource: tables.yml }

services:
    sheer.minical.listener:
        class: sheer\minical\event\listener
        arguments:
            - @template
            - @request
            - @user
            - @auth
            - @dbal.conn
            - @config
            - %core.table_prefix%
            - %core.root_path%
            - %core.php_ext%
            - %tables.minical%
        tags:
            - { name: event.listener }

    sheer.minical.cron.task.tidy_minical:
        class: sheer\minical\cron\task\tidy_minical
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @log
            - %tables.minical%
        calls:
            - [set_name, [cron.task.core.sheer_tidy_minical]]
        tags:
            - { name: cron.task }
