services:
    sheer.minical.listener:
        class: sheer\minical\event\listener
        arguments:
            - @template
            - @request
            - @user
            - @auth
            - @dbal.conn
            - @config
            - %core.table_prefix%
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
